site_name: omcm Documentation
repo_url: https://github.com/linewx/omcm/
copyright: 2020 - ganlin lu
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage: usage.md
  - About: about.md
theme: readthedocs
